create type "public"."vehicleType" as enum ('CAR', 'TRUCK', 'SUV');

create table "public"."announcements" (
    "id" integer generated by default as identity not null,
    "title" text,
    "message" text,
    "createdAt" timestamp with time zone not null default now(),
    "modifiedAt" timestamp with time zone not null default now()
);


alter table "public"."announcements" enable row level security;

create table "public"."notifications" (
    "id" bigint generated by default as identity not null,
    "userId" uuid not null,
    "title" text,
    "message" text,
    "createdAt" timestamp with time zone not null default now(),
    "modifiedAt" timestamp with time zone not null default now()
);


alter table "public"."notifications" enable row level security;

create table "public"."vehicleFinanceSheets" (
    "id" integer generated by default as identity not null,
    "userId" uuid not null,
    "sheetName" text,
    "salesConsultant" text,
    "dealershipName" text,
    "vehicleType" "vehicleType" not null default 'CAR'::"vehicleType",
    "shareableKey" text,
    "msrp" real,
    "fees" real,
    "discounts" real,
    "rebates" real,
    "downPayment" real,
    "salesTaxPercent" real,
    "interestRate" real,
    "financeTerm" smallint,
    "createdAt" timestamp with time zone default now(),
    "modifiedAt" timestamp with time zone default now(),
    "startDate" timestamp with time zone,
    "contactEmail" text,
    "contactPhone" text,
    "extraPaymentsJson" text
);


alter table "public"."vehicleFinanceSheets" enable row level security;

create table "public"."vehicleLeaseSheets" (
    "id" integer generated by default as identity not null,
    "userId" uuid not null,
    "sheetName" text,
    "salesConsultant" text,
    "dealershipName" text,
    "vehicleType" "vehicleType" not null default 'CAR'::"vehicleType",
    "shareableKey" text,
    "msrp" real,
    "dealerContribution" real,
    "tradeIn" real,
    "docFee" real,
    "acquisitionFee" real,
    "miscFees" real,
    "leaseCash" real,
    "downPayment" real,
    "moneyFactor" real,
    "salesTaxPercent" real,
    "residualPercent" real,
    "leaseTerm" smallint,
    "startDate" timestamp with time zone,
    "createdAt" timestamp with time zone not null default now(),
    "modifiedAt" timestamp with time zone not null default now(),
    "contactEmail" text,
    "contactPhone" text
);


alter table "public"."vehicleLeaseSheets" enable row level security;

alter table "public"."profiles" drop column "avatar_url";

alter table "public"."profiles" drop column "full_name";

alter table "public"."profiles" drop column "updated_at";

alter table "public"."profiles" add column "avatarUrl" text;

alter table "public"."profiles" add column "firstName" text;

alter table "public"."profiles" add column "lastName" text;

alter table "public"."profiles" add column "updatedAt" timestamp with time zone;

CREATE UNIQUE INDEX announcements_pkey ON public.announcements USING btree (id);

CREATE UNIQUE INDEX notifications_pkey ON public.notifications USING btree (id);

CREATE UNIQUE INDEX "vehicleFinanceSheet_pkey" ON public."vehicleFinanceSheets" USING btree (id);

CREATE UNIQUE INDEX "vehicleLeaseEstimate_id_key" ON public."vehicleLeaseSheets" USING btree (id);

CREATE UNIQUE INDEX "vehicleLeaseEstimate_pkey" ON public."vehicleLeaseSheets" USING btree (id);

alter table "public"."announcements" add constraint "announcements_pkey" PRIMARY KEY using index "announcements_pkey";

alter table "public"."notifications" add constraint "notifications_pkey" PRIMARY KEY using index "notifications_pkey";

alter table "public"."vehicleFinanceSheets" add constraint "vehicleFinanceSheet_pkey" PRIMARY KEY using index "vehicleFinanceSheet_pkey";

alter table "public"."vehicleLeaseSheets" add constraint "vehicleLeaseEstimate_pkey" PRIMARY KEY using index "vehicleLeaseEstimate_pkey";

alter table "public"."notifications" add constraint "notifications_userId_fkey" FOREIGN KEY ("userId") REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."notifications" validate constraint "notifications_userId_fkey";

alter table "public"."vehicleFinanceSheets" add constraint "vehicleFinanceSheets_userId_fkey" FOREIGN KEY ("userId") REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."vehicleFinanceSheets" validate constraint "vehicleFinanceSheets_userId_fkey";

alter table "public"."vehicleLeaseSheets" add constraint "vehicleLeaseEstimate_id_key" UNIQUE using index "vehicleLeaseEstimate_id_key";

alter table "public"."vehicleLeaseSheets" add constraint "vehicleLeaseSheets_userId_fkey" FOREIGN KEY ("userId") REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."vehicleLeaseSheets" validate constraint "vehicleLeaseSheets_userId_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  insert into public.profiles (id, "firstName", "lastName", "avatarUrl")
  values (
    new.id, 
    new.raw_user_meta_data->>'firstName',
    new.raw_user_meta_data->>'lastName',
    new.raw_user_meta_data->>'avatarUrl'
  );
  
  return new;
end;
$function$
;

-- Create the trigger
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

grant delete on table "public"."announcements" to "anon";

grant insert on table "public"."announcements" to "anon";

grant references on table "public"."announcements" to "anon";

grant select on table "public"."announcements" to "anon";

grant trigger on table "public"."announcements" to "anon";

grant truncate on table "public"."announcements" to "anon";

grant update on table "public"."announcements" to "anon";

grant delete on table "public"."announcements" to "authenticated";

grant insert on table "public"."announcements" to "authenticated";

grant references on table "public"."announcements" to "authenticated";

grant select on table "public"."announcements" to "authenticated";

grant trigger on table "public"."announcements" to "authenticated";

grant truncate on table "public"."announcements" to "authenticated";

grant update on table "public"."announcements" to "authenticated";

grant delete on table "public"."announcements" to "service_role";

grant insert on table "public"."announcements" to "service_role";

grant references on table "public"."announcements" to "service_role";

grant select on table "public"."announcements" to "service_role";

grant trigger on table "public"."announcements" to "service_role";

grant truncate on table "public"."announcements" to "service_role";

grant update on table "public"."announcements" to "service_role";

grant delete on table "public"."notifications" to "anon";

grant insert on table "public"."notifications" to "anon";

grant references on table "public"."notifications" to "anon";

grant select on table "public"."notifications" to "anon";

grant trigger on table "public"."notifications" to "anon";

grant truncate on table "public"."notifications" to "anon";

grant update on table "public"."notifications" to "anon";

grant delete on table "public"."notifications" to "authenticated";

grant insert on table "public"."notifications" to "authenticated";

grant references on table "public"."notifications" to "authenticated";

grant select on table "public"."notifications" to "authenticated";

grant trigger on table "public"."notifications" to "authenticated";

grant truncate on table "public"."notifications" to "authenticated";

grant update on table "public"."notifications" to "authenticated";

grant delete on table "public"."notifications" to "service_role";

grant insert on table "public"."notifications" to "service_role";

grant references on table "public"."notifications" to "service_role";

grant select on table "public"."notifications" to "service_role";

grant trigger on table "public"."notifications" to "service_role";

grant truncate on table "public"."notifications" to "service_role";

grant update on table "public"."notifications" to "service_role";

grant delete on table "public"."vehicleFinanceSheets" to "anon";

grant insert on table "public"."vehicleFinanceSheets" to "anon";

grant references on table "public"."vehicleFinanceSheets" to "anon";

grant select on table "public"."vehicleFinanceSheets" to "anon";

grant trigger on table "public"."vehicleFinanceSheets" to "anon";

grant truncate on table "public"."vehicleFinanceSheets" to "anon";

grant update on table "public"."vehicleFinanceSheets" to "anon";

grant delete on table "public"."vehicleFinanceSheets" to "authenticated";

grant insert on table "public"."vehicleFinanceSheets" to "authenticated";

grant references on table "public"."vehicleFinanceSheets" to "authenticated";

grant select on table "public"."vehicleFinanceSheets" to "authenticated";

grant trigger on table "public"."vehicleFinanceSheets" to "authenticated";

grant truncate on table "public"."vehicleFinanceSheets" to "authenticated";

grant update on table "public"."vehicleFinanceSheets" to "authenticated";

grant delete on table "public"."vehicleFinanceSheets" to "service_role";

grant insert on table "public"."vehicleFinanceSheets" to "service_role";

grant references on table "public"."vehicleFinanceSheets" to "service_role";

grant select on table "public"."vehicleFinanceSheets" to "service_role";

grant trigger on table "public"."vehicleFinanceSheets" to "service_role";

grant truncate on table "public"."vehicleFinanceSheets" to "service_role";

grant update on table "public"."vehicleFinanceSheets" to "service_role";

grant delete on table "public"."vehicleLeaseSheets" to "anon";

grant insert on table "public"."vehicleLeaseSheets" to "anon";

grant references on table "public"."vehicleLeaseSheets" to "anon";

grant select on table "public"."vehicleLeaseSheets" to "anon";

grant trigger on table "public"."vehicleLeaseSheets" to "anon";

grant truncate on table "public"."vehicleLeaseSheets" to "anon";

grant update on table "public"."vehicleLeaseSheets" to "anon";

grant delete on table "public"."vehicleLeaseSheets" to "authenticated";

grant insert on table "public"."vehicleLeaseSheets" to "authenticated";

grant references on table "public"."vehicleLeaseSheets" to "authenticated";

grant select on table "public"."vehicleLeaseSheets" to "authenticated";

grant trigger on table "public"."vehicleLeaseSheets" to "authenticated";

grant truncate on table "public"."vehicleLeaseSheets" to "authenticated";

grant update on table "public"."vehicleLeaseSheets" to "authenticated";

grant delete on table "public"."vehicleLeaseSheets" to "service_role";

grant insert on table "public"."vehicleLeaseSheets" to "service_role";

grant references on table "public"."vehicleLeaseSheets" to "service_role";

grant select on table "public"."vehicleLeaseSheets" to "service_role";

grant trigger on table "public"."vehicleLeaseSheets" to "service_role";

grant truncate on table "public"."vehicleLeaseSheets" to "service_role";

grant update on table "public"."vehicleLeaseSheets" to "service_role";


