export const LEASE_FORM_FIELDS = {
	// database fields
	USER_ID: 'userId',
	SHEET_NAME: 'sheetName',
	SALES_CONSULTANT: 'salesConsultant',
	DEALERSHIP_NAME: 'dealershipName',
	VEHICLE_TYPE: 'vehicleType',
	SHAREABLE_KEY: 'shareableKey',
	MSRP: 'msrp',
	DEALER_CONTRIBUTION: 'dealerContribution',
	TRADE_IN: 'tradeIn',
	DOC_FEE: 'docFee',
	ACQUISITION_FEE: 'acquisitionFee',
	MISC_FEES: 'miscFees',
	LEASE_CASH: 'leaseCash',
	DOWN_PAYMENT: 'downPayment',
	MONEY_FACTOR: 'moneyFactor',
	SALES_TAX_PERCENT: 'salesTaxPercent',
	RESIDUAL_PERCENT: 'residualPercent',
	LEASE_TERM: 'leaseTerm',
	START_DATE: 'startDate',
	CONTACT_EMAIL: 'contactEmail',
	CONTACT_PHONE: 'contactPhone',

	CREATED_AT: 'createdAt',
	MODIFIED_AT: 'modifiedAt',

	// calculated fields
	RESIDUAL_AMOUNT: 'residualAmount',
	INTEREST_RATE: 'interestRate',
	FINAL_DEALER_PRICE: 'finalDealerPrice',
	GROSS_CAP_COST: 'grossCapCost',
	NET_CAP_COST: 'netCapCost',
	PRINCIPAL_AMOUNT: 'principalAmount',
	PRINCIPAL_PAYMENT: 'principalPayment',
	RESIDUAL_MONTHLY_INTEREST_PAYMENT: 'residualMonthlyInterestPayment',
	TOTAL_SALES_TAX: 'totalSalesTax',
	MONTHLY_SALES_TAX: 'monthlySalesTax',
	LEASE_PAYMENT: 'leasePayment',
	CASH_DUE_AT_SIGNING: 'cashDueAtSigning',
	TOTAL_LEASE_COST: 'totalLeaseCost',
}

export const FINANCE_FORM_FIELDS = {
	// database fields
	USER_ID: 'userId',
	SHEET_NAME: 'sheetName',
	SALES_CONSULTANT: 'salesConsultant',
	DEALERSHIP_NAME: 'dealershipName',
	VEHICLE_TYPE: 'vehicleType',
	SHAREABLE_KEY: 'shareableKey',
	MSRP: 'msrp',
	FEES: 'fees',
	DISCOUNTS: 'discounts',
	REBATES: 'rebates',
	DOWN_PAYMENT: 'downPayment',
	SALES_TAX_PERCENT: 'salesTaxPercent',
	INTEREST_RATE: 'interestRate',
	FINANCE_TERM: 'financeTerm',
	START_DATE: 'startDate',
	CONTACT_EMAIL: 'contactEmail',
	CONTACT_PHONE: 'contactPhone',

	CREATED_AT: 'createdAt',
	MODIFIED_AT: 'modifiedAt',

	// computed fields
	PURCHASE_PRICE: 'purchasePrice',
	SALES_TAX_AMOUNT: 'salesTaxAmount',
	LOAN_AMOUNT: 'loanAmount',
	MONTHLY_PAYMENT: 'monthlyPayment',
	INTEREST_AMOUNT: 'interestAmount',
	PAYMENTS_TOTAL: 'paymentsTotal',
	BASE_AMORTIZATION: 'baseAmortization',
	BASE_AMORTIZATION_DETAILS: 'baseAmortizationDetails',
	REDUCED_AMORTIZATION: 'reducedAmortization',
	REDUCED_AMORTIZATION_DETAILS: 'reducedAmortizationDetails',

	EXTRA_PAYMENTS_JSON: 'extraPaymentsJson',
	EXTRA_PAYMENTS: 'extraPaymentsParsed',
	EXTRA_PAYMENTS_FIELDS: {
		PAYMENT_AMOUNT: 'paymentAmount',
		START_MONTH: 'startMonth',
		END_MONTH: 'endMonth',
	},
}
