import { desc, eq } from 'drizzle-orm';
import { Hono } from 'hono';

import { db } from '../db/client.js';
import {
	mortgageSheets,
	retailers,
	trackedProducts,
	vehicleFinanceSheets,
	vehicleLeaseSheets,
} from '../db/schema.js';
import { serializeRow, serializeRows } from '../db/serialize.js';
import type { AppEnv } from '../http/app.js';
import { currentUser, requireAuth } from '../http/auth-middleware.js';

/**
 * Dashboard summary.
 *
 * Ports the inline closure at routes/api.php:193. The original loaded every
 * sheet and every tracked product in full, counted them in PHP, then returned
 * only the first three of each - so a user with hundreds of records transferred
 * all of them to produce four integers.
 *
 * Counts and three-row queries are issued separately here. The response shape
 * is unchanged, which is what the clients depend on; only the amount of data
 * moved to produce it differs.
 *
 * The queries are written out rather than generated by a helper: Drizzle's types
 * are per-table, so a generic version needs casts that defeat the point of
 * having them.
 */

export const dashboardRoutes = new Hono<AppEnv>();

dashboardRoutes.use('*', requireAuth);

dashboardRoutes.get('/stats', async (c) => {
	const user = currentUser(c);
	const d = db();

	const [
		financeCount,
		leaseCount,
		mortgageCount,
		watchCount,
		recentFinance,
		recentLease,
		recentMortgage,
		recentWatch,
	] = await Promise.all([
		d.$count(vehicleFinanceSheets, eq(vehicleFinanceSheets.userId, user.id)),
		d.$count(vehicleLeaseSheets, eq(vehicleLeaseSheets.userId, user.id)),
		d.$count(mortgageSheets, eq(mortgageSheets.userId, user.id)),
		d.$count(trackedProducts, eq(trackedProducts.userId, user.id)),

		d
			.select()
			.from(vehicleFinanceSheets)
			.where(eq(vehicleFinanceSheets.userId, user.id))
			.orderBy(desc(vehicleFinanceSheets.createdAt), desc(vehicleFinanceSheets.id))
			.limit(3),

		d
			.select()
			.from(vehicleLeaseSheets)
			.where(eq(vehicleLeaseSheets.userId, user.id))
			.orderBy(desc(vehicleLeaseSheets.createdAt), desc(vehicleLeaseSheets.id))
			.limit(3),

		d
			.select()
			.from(mortgageSheets)
			.where(eq(mortgageSheets.userId, user.id))
			.orderBy(desc(mortgageSheets.createdAt), desc(mortgageSheets.id))
			.limit(3),

		// Tracked products carry their retailer, as the original's
		// with('retailer') eager load did - minus the credential columns the
		// model kept in $hidden.
		d
			.select({
				product: trackedProducts,
				retailer: {
					id: retailers.id,
					name: retailers.name,
					slug: retailers.slug,
					logo_url: retailers.logoUrl,
					is_active: retailers.isActive,
					coming_soon: retailers.comingSoon,
					created_at: retailers.createdAt,
					updated_at: retailers.updatedAt,
				},
			})
			.from(trackedProducts)
			.innerJoin(retailers, eq(trackedProducts.retailerId, retailers.id))
			.where(eq(trackedProducts.userId, user.id))
			.orderBy(desc(trackedProducts.createdAt), desc(trackedProducts.id))
			.limit(3),
	]);

	return c.json({
		finance_sheets_count: Number(financeCount),
		lease_sheets_count: Number(leaseCount),
		mortgage_sheets_count: Number(mortgageCount),
		tracked_products_count: Number(watchCount),
		recent_finance_sheets: serializeRows(recentFinance),
		recent_lease_sheets: serializeRows(recentLease),
		recent_mortgage_sheets: serializeRows(recentMortgage),
		recent_tracked_products: recentWatch.map((row) => ({
			...serializeRow(row.product),
			retailer: serializeRow(row.retailer),
		})),
	});
});
